name: build

on: [push, pull_request]

env:
  # color output for pytest and tox
  PYTEST_ADDOPTS: "--color=yes"
  PY_COLORS: 1

jobs:
  test:
    name: Test - ${{ matrix.config.python }} - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}-latest

    strategy:
      matrix:
        config:
          - os: ubuntu
            python: "3.7"
          - os: ubuntu
            python: "3.8"
          - os: ubuntu
            python: "3.9"
          - os: ubuntu
            python: "3.10"
          - os: macos
            python: "3.7"
          - os: windows
            python: "3.7"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.config.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python }}
      - name: Set up Pip cache (Linux)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Pip cache (macOS)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup pip cache (Windows)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install locale (Linux)
        if: startsWith(runner.os, 'Linux')
        run: sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.9.2"
      - name: Install tox
        run: python -m pip install -U pip tox
      - name: Info
        run: |
          echo "=====  PYTHON  ====="
          python --version
          echo "=====  PANDOC  ====="
          pandoc --version | head -2
      - name: Run tests
        run: tox -e py${{ matrix.config.python }}


  step-test:
    name: Step Test
    runs-on: ubuntu-latest

    steps:
      - name: Failure
        id: failure
        run: exit 1
        continue-on-error: true
      - name: Success
        id: success
        run: exit 0
        continue-on-error: true
      - name: Check failure
        if: steps.failure.outcome=='failure'
        run: echo "failure failed"
      - name: Check success
        if: steps.success.outcome=='success'
        run: echo "success succeeded"
      - name: Should not run because of failure
        if: steps.failure.outcome=='success'
        run: echo "should not run"
      - name: Should not run because of success
        if: steps.success.outcome=='failure'
        run: echo "should not run"


  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set pip cache (Linux)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install tox
        run: python -m pip install -U pip tox
      - name: Check
        run: tox -e flake8


  docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Set pip cache (Linux)
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install tox
        run: python -m pip install -U pip tox
      - name: Check
        run: tox -e docs


  deploy:
    name: Deploy
    needs: [test, lint, docs]
    runs-on: ubuntu-latest
    if: ${{ github.ref=='refs/heads/master' && github.event_name!='pull_request' }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Check release
        id: check_release
        run: |
          python -m pip install pip --upgrade
          pip install poetry
          pip install githubrelease
          pip install --pre autopub
          autopub check
        continue-on-error: true
      - name: Publish
        if: ${{ steps.check_release.outcome=='success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          git remote set-url origin https://$GITHUB_TOKEN@github.com/${{ github.repository }}
          autopub prepare
          poetry build
          autopub commit
          autopub githubrelease
          poetry publish -u __token__ -p $PYPI_PASSWORD
